### PR TITLE
NineQuery9_GetData(): Do not flush if the application does not request it.

### PR DESCRIPTION
**Pull request by xxxbxxx**
Seems to behave more like windows to me. but there's probably some reason for original code?
(also, I get better fps in some cases.)

### CODE REVIEW

**Comment by axeldavy** [comment]
The gallium api always flush, so it's as if the application was always indicating the flush flag

however your patch doesn't seem the windows way at all.
The windows way seems to flush one time, and then loop on GetData to get the result

you patch would make the first call blocking until done.

**Comment by xxxbxxx** [comment]
Ah I think I see what you mean. I'll try to make some more tests on windows.

The problem I was trying to fix was GetData(, 0) on querry timestamps is blocking the program, which seems is not the case on windows. -> makes the cpu wait for gpu and break parallelisation.
So, I removed 
wait_query_result |= This->type == D3DQUERYTYPE_TIMESTAMP;

And then I had some jumpy framerate when in "cpu waits for gpu at end of frame" mode in the app, and interpreting the FLUSH as "wait_query_result" did solve the issue.

I'll investigate some more, and try to understand what's going on and how it's supposed to work.

Maybe the correct fix is 
```
if ((dwGetDataFlags & D3DGETDATA_FLUSH) && (This->type == D3DQUERYTYPE_TIMESTAMP)
  wait_query_result = TRUE;
```

**Comment by xxxbxxx** [comment]
Ok. my mistake: the initial code that blocks on timesstamp even when no flush is requested is indeed what windows do. (with AMD driver at least)

(And the jumpy framerate was a wrong behaviour in the client app while waiting for gpu query repeatedly.)

However, I reckon I did get  a better framerate  (when wait_query_result was always false). 
I'll double check to see if there's an other reason. And I'll try to get around reinstalling wine and see what happens with other games.

**Comment by axeldavy** [comment]
If I understand we have currently Amd behaviour, but not Nvidia behaviour.

Isn't it more same to implement the Amd behaviour here ? If an app reads the vendor id to have different behaviour on Amd or Nvidia, it will be better not having the Nvidia behaviour on Amd.

**Comment by xxxbxxx** [comment]
So.. 
The idea is that some games use timestamp queries for measuring a few things during runtime.
(say, to measure some part of the render and adapt quality vs framerate tradeoff dynamically. For instance, to render particles effects at a lower resolution if many are spawned at the same time. 
Or just to do profiling/telemetrics. )

To do so the program issues some queries together with the rendering. And then comes at a later time (when drawing a frame later on, the next one or further down.) to read the result.  So, for that usage, that "is query result ready?" call blocks the program instead of just postponing to the next frame the reading of the result.  

So depending on the program (whether it is cpu or gpu limited, how extensively it uses queries...) this can have some effect on the fps. If it reads the result on the start of rendering a frame on the cpu (to be able to reuse the queries in the new frame once they become available), then the blocking call presents parallelism between cpu starting to issue draw calls for a new frame while the gpu finishing to draw the previous one.

However in pratice it doesn't make a big difference, because: 
 - usually programs are gpu limited and the actual cpudisables work to issue the frame is not huge...
 - given the amd windows drivers behaviour , games already pay attention to this.
I still made some tests with a couple of games, and some do show a very small improvement. 
 (The biggest change I observed was looking at the ceiling in 'life is strange' (unreal engine) in a pretty heavy scene - ie, the best case: large cpu scene set-up,  very fast actual gpu rendering - did go from 48fps to 57fps. but when actually looking at the scene it more like from 17fps to 18fps... )
But this is not very reliable as I don't quite understand what's going on between wine, gnome-shell and so on...

The caveat of the change is that it may break synchronization on programs relying on the amd driver behaviour. But that's unlikely, I guess, given that they would also not work properly on nvidia drivers.

**Comment by axeldavy** [comment]
Some games do actually have different rendering path depending on drivers.

Can you tell me your interpretation of the flush flag ? Reading the documentation, I got the interpretation every request should be called at least one time with the flush flag, else you can't expect to get a result.

**Comment by xxxbxxx** [comment]
well my interpretation is that just doing GetData(,0) will not provoke a flush on it's own (and to me this "flush" is "sending the prepared commands to the graphics card for processing" ) 
so if you want to be sure to eventually get a result, especially if you wait without issuing other api calls, you need to explicitly request a flush.

(two more things:  
 - Initially I wanted to fix this because when I enabled the in-game profiler in "shootmania" game to see where the time is spent, I noticed an unexpected large time slice
 - I don't quite understand how/why the windows amd driver behaviour ended being as it is, so maybe there's something else to this?)

**Comment by axeldavy** [comment]
Since it is about performance improvement, can you:
. Change the commit msg to reflect it is about improving the performance of this particular query
. In the comments in the code, add we choose the NV behaviour because it leads to better performance for some apps.

**Comment by xxxbxxx** [comment]
I did some more testing, and this time I observed amd driver on windows also *not* block on getdata() and return false when "flush" flag was not set. I don't know why the result was different the previous time (and I'm pretty sure I did double check at the time since I was very surprised).   meh...

I also did test a couple more games in wine: "portal 2" is unaffected,  "metro last list" gets some more fps.

**Comment by axeldavy** [comment]
It's strange apps are affected at all. I was thinking that query was mostly for development.

**Pull request merged**
