### PR TITLE
st/nine: fix truncating cast of D3DUSAGE_QUERY_SRGBWRITE to boolean.

### PR DESCRIPTION
**Pull request by xxxbxxx**

### CODE REVIEW

**Comment by xxxbxxx** [comment]
Definitely a bug, the result the bool passed to the function was false hen Usage was D3DUSAGE_QUERY_SRGBWRITE (0x40000). 

typedef unsigned char boolean;

and the visible bug was the program picked a format after checking it supported SRGB (instead of falling back to another supported actually supporting it), and as it didn't -> washed out colrs.

**Comment by axeldavy** [comment]
oh, I see. Nice catch !

Since the culprit patch isn't merged in mesa master yet, it would be better to amend it:
https://github.com/iXit/Mesa-3D/commit/18740d91e289d12f5a348e524dfa309bd5b27f9b

Do you mind If I put your fix in it, instead of merging your patch ?

**Comment by xxxbxxx** [comment]
sure go ahead.

(I'll have a quick look at if can spot other occurence of similar issues in the rest of the code.)

**Comment by axeldavy** [comment]
done

**Pull request closed without merging**
