### PR TITLE
fix some wine tests

### PR DESCRIPTION
**Pull request by siro20**
this fixes visual.c multiple_rendertargets_test()
this fixes device test_unused_declaration_type()

### CODE REVIEW

**Comment by axeldavy** [comment]
Here some comments:

Put more more comments to explain what you do and why you do it that way. It took me some time for example for the clear patch to understand the beginning of the patch.

Check the syntax (an 'if(!Count)! instead of 'if (!Count)')

For the two first patches, I dislike the approach taken. Reading the original code, the 'nine_update_state(This, NINE_STATE_FB);' is to be interpreted as 'bound me the buffers I want' and that's also why it accesses 'This->state.fb.cbufs[i]' directly.

I think instead update_framebuffer should be cut into pieces, so that clear could get the cbufs via the same function than update_framebuffer (to avoid duplicated code), and at the end clear would add to the state to changed NINE_STATE_FB if the ps rt_mask differs. It would be the best to reduce overhead.
That's probably too much to ask to you, so just add a TODO: refactor update_framebuffer to avoid code duplication here in you NineDevice9_Clear patch

**Comment by axeldavy** [comment]
what happened to the previous patches ?

**Comment by siro20** [comment]
I'm working on the previous patches :-)

**Comment by axeldavy** [comment]
Did you have a patch for Clear ?

Can you put it somewhere, we have found another issues with Clear and I want make patch taking into account what we found and what you found is wrong with current code.

**Pull request merged**
