### PR TITLE
Send upstream

### PR DESCRIPTION
**Pull request by siro20**
Please review

### CODE REVIEW

**Comment by EoD** [comment]
@siro20 I guess you want to use Mismatch instead of Missmatch  :)

**Comment by axeldavy** [comment]
The patches I didn't comment look good

(however some commit messages are a bit too alarmist:
"The threadpool will be able to call functions in WINE without
crashing the wineserver" -> it could mean that it crashes consistently.
something like "Creating the thread with wine prevents some rarely occuring crashes"
seems more appropriate)

**Comment by siro20** [comment]
pthread_join waits for the thread to terminate. It doesn't signal that it has to terminate. Same for NineSwapChain9_WaitForWineThread which waits for the thread to terminate.

**Comment by axeldavy** [comment]
LGTM. Small nitpicking for commit messages (Is "Implement" really appropriate here..?) Anyway, I'm going to push.

**Pull request merged**
