### PR TITLE
bug report / work around for wrong units in TIMESTAMP query

### PR DESCRIPTION
**Pull request by xxxbxxx**

### CODE REVIEW

**Comment by tizbac** [comment]
This looks wrong, on gallium disjoint query returns both frequency and if it's disjoint, d3dapps should first query the frequency and then use that as Hz value, it should be correct as it is now

**Comment by xxxbxxx** [comment]
yes there's no problem with D3DQUERYTYPE_TIMESTAMPFREQ per se.

What I mean is:
as shown in this example (found with a google search) http://www.junkship.net/News/2012/07/03/timing-is-everything
```
            //The final timing value in seconds.
            double value = ((double)diff/frequency);
``` 
So the value returned by D3DQUERYTYPE_TIMESTAMP must by a number of ticks at D3DQUERYTYPE_TIMESTAMPFREQ frequency.

However in gallium (or is it only r600g?)  the value for PIPE_QUERY_TIMESTAMP  is in microseconds, not in multiples of frequency
see: https://github.com/iXit/Mesa-3D/blob/master/src/gallium/drivers/radeon/r600_query.c#L751

**Comment by tizbac** [comment]
Then it maybe r600 bug, check AMD docs regarding queries
Il 11/feb/2015 18:48 "xxxbxxx" <notifications@github.com> ha scritto:

**Comment by axeldavy** [comment]
On the mesa mailing list there are patches that changes the R600/SI implementation of this query, perhaps you could check if it behaves ok with them ?

**Comment by xxxbxxx** [comment]
btw, is there any specification / documentation for gallium that would define such things like what is "expected" in "Convert the time to expected units." ?
or is it only the source code?

**Comment by axeldavy** [comment]
The doc says:
``PIPE_QUERY_TIMESTAMP`` returns a device/driver internal timestamp,
scaled to nanoseconds, recorded after all commands issued prior to
``end_query`` have been processed.
This query does not require a call to ``begin_query``.
The result is an unsigned 64-bit integer.

``PIPE_QUERY_TIMESTAMP_DISJOINT`` can be used to check the
internal timer resolution and whether the timestamp counter has become
unreliable due to things like throttling etc. - only if this is FALSE
a timestamp query (within the timestamp_disjoint query) should be trusted.
The result is a 64-bit integer specifying the timer resolution in Hz,
followed by a boolean value indicating whether the timestamp counter
is discontinuous or disjoint.

**Comment by xxxbxxx** [comment]
mmmmm. So, I had a look at the other drivers and state trackers.
 - all drivers seem to return 1000000000 ns for   PIPE_QUERY_TIMESTAMP_DISJOINT except r600g that retrieve hardware clock.
 - all drivers return nanoseconds timestamps.  which are then passed through  to GL_TIMESTAMP querries
 - no one uses PIPE_QUERY_TIMESTAMP_DISJOINT except nine.

given the doc you provide and given the current uses, then I would say r600g should also return 1000000000...  which make the whole PIPE_QUERY_TIMESTAMP_DISJOINT thing pretty useless...

**Comment by xxxbxxx** [comment]
mmmm. not so sure. "internal timer resolution" may as well mean the hardware clock.  Then it should be nine that shouldn't return this value to D3d calls, but  1000000000 ns which is the actaully time stamps resolution.  now, to find where microsoft defines the timestamp unit..

**Comment by xxxbxxx** [comment]
So.. msdn seems pretty buggy on this one 
* D3DQUERYTYPE_TIMESTAMP    Returns a 64-bit timestamp.
* D3DQUERYTYPE_TIMESTAMPDISJOINT    Use this query to notify an application if the counter frequency has changed from the D3DQUERYTYPE_TIMESTAMP.
* D3DQUERYTYPE_TIMESTAMPFREQ    This query result is TRUE if the values from D3DQUERYTYPE_TIMESTAMP queries cannot be guaranteed to be continuous throughout the duration of the D3DQUERYTYPE_TIMESTAMPDISJOINT query. Otherwise, the query result is FALSE.

????

checked wine code too. and it always returns  1000000000  (as it is using GL querry which is in nanoseconds)
```
static const struct wined3d_query_data_timestamp_disjoint disjoint_data = {FALSE, 1000 * 1000 * 1000};
.....
```

so I'd say my initial patch is not so bad...

**Comment by axeldavy** [comment]
ok, let's go for this patch, but match the comment with what we discovered

**Pull request merged**
